### ISSUE TITLE
rancher installation via airgap script failing

### ISSUE THREAD

**Issue by irgama** [rancherfederal/rke_airgap_install#3]
Release "rancher" does not exist. Installing it now.
Error: chart requires kubeVersion: < 1.26.0-0 which is incompatible with Kubernetes v1.26.7+rke2r1

It looks like rancher needs to be at least version 2.7.5 to work with 1.26.

Also, I ran into an error when trying to do this initially, where I got the following error. However, I just needed to run "source ~/.bashrc". Still, I think that should be added to the script for installing rancher/longhorn/etc. or in the documentation.

  - deploying rancher
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused

**Comment by clemenko** [comment]
just updated rancher to 2.7.5. this should work now.
